[build]
  publish = "."

[[redirects]]
  from = "/map"
  to   = "/map/index.html"
  status = 200

[[redirects]]
  from = "/cities"
  to   = "/cities/index.html"
  status = 200

[[redirects]]
  from = "/shareholders"
  to   = "/shareholders/index.html"
  status = 200

[[redirects]]
  from = "/speed"
  to   = "/speed/index.html"
  status = 200

[[redirects]]
  from = "/ir-salary"
  to   = "/ir-salary/index.html"
  status = 200

[[redirects]]
  from = "/gov-news"
  to   = "/gov-news/index.html"
  status = 200
